// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shipping/shipping.proto

package shipping

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item struct {
	ProductCode          string   `protobuf:"bytes,1,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	UnitPrice            float32  `protobuf:"fixed32,2,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Quantity             int32    `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_218d76102d381bfb, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetProductCode() string {
	if m != nil {
		return m.ProductCode
	}
	return ""
}

func (m *Item) GetUnitPrice() float32 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

func (m *Item) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type CreateShippingRequest struct {
	PurchaseId           int64    `protobuf:"varint,1,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	Items                []*Item  `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateShippingRequest) Reset()         { *m = CreateShippingRequest{} }
func (m *CreateShippingRequest) String() string { return proto.CompactTextString(m) }
func (*CreateShippingRequest) ProtoMessage()    {}
func (*CreateShippingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_218d76102d381bfb, []int{1}
}

func (m *CreateShippingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShippingRequest.Unmarshal(m, b)
}
func (m *CreateShippingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShippingRequest.Marshal(b, m, deterministic)
}
func (m *CreateShippingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShippingRequest.Merge(m, src)
}
func (m *CreateShippingRequest) XXX_Size() int {
	return xxx_messageInfo_CreateShippingRequest.Size(m)
}
func (m *CreateShippingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShippingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShippingRequest proto.InternalMessageInfo

func (m *CreateShippingRequest) GetPurchaseId() int64 {
	if m != nil {
		return m.PurchaseId
	}
	return 0
}

func (m *CreateShippingRequest) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type CreateShippingResponse struct {
	DeadlineInDays       int64    `protobuf:"varint,1,opt,name=deadline_in_days,json=deadlineInDays,proto3" json:"deadline_in_days,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateShippingResponse) Reset()         { *m = CreateShippingResponse{} }
func (m *CreateShippingResponse) String() string { return proto.CompactTextString(m) }
func (*CreateShippingResponse) ProtoMessage()    {}
func (*CreateShippingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_218d76102d381bfb, []int{2}
}

func (m *CreateShippingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShippingResponse.Unmarshal(m, b)
}
func (m *CreateShippingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShippingResponse.Marshal(b, m, deterministic)
}
func (m *CreateShippingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShippingResponse.Merge(m, src)
}
func (m *CreateShippingResponse) XXX_Size() int {
	return xxx_messageInfo_CreateShippingResponse.Size(m)
}
func (m *CreateShippingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShippingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShippingResponse proto.InternalMessageInfo

func (m *CreateShippingResponse) GetDeadlineInDays() int64 {
	if m != nil {
		return m.DeadlineInDays
	}
	return 0
}

func init() {
	proto.RegisterType((*Item)(nil), "Item")
	proto.RegisterType((*CreateShippingRequest)(nil), "CreateShippingRequest")
	proto.RegisterType((*CreateShippingResponse)(nil), "CreateShippingResponse")
}

func init() {
	proto.RegisterFile("shipping/shipping.proto", fileDescriptor_218d76102d381bfb)
}

var fileDescriptor_218d76102d381bfb = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xd1, 0xcb, 0x4b, 0x03, 0x31,
	0x10, 0x06, 0x70, 0xb7, 0xb5, 0xa5, 0x9d, 0x8a, 0x48, 0xc0, 0x76, 0xa9, 0x88, 0xeb, 0x9e, 0xf6,
	0xe2, 0x2e, 0xd6, 0x93, 0x8f, 0x53, 0x2b, 0x48, 0x6f, 0xb2, 0xe2, 0xc5, 0xcb, 0x92, 0x26, 0x43,
	0x3b, 0xd0, 0x26, 0x69, 0x1e, 0x42, 0xff, 0x7b, 0xe9, 0x63, 0x45, 0xa4, 0xb7, 0xe4, 0x07, 0xf9,
	0xbe, 0x21, 0x03, 0x03, 0xb7, 0x20, 0x63, 0x48, 0xcd, 0x8b, 0xfa, 0x90, 0x1b, 0xab, 0xbd, 0x4e,
	0x25, 0x9c, 0x4e, 0x3d, 0xae, 0xd8, 0x2d, 0x9c, 0x19, 0xab, 0x65, 0x10, 0xbe, 0x12, 0x5a, 0x62,
	0x1c, 0x25, 0x51, 0xd6, 0x2d, 0x7b, 0x07, 0x9b, 0x68, 0x89, 0xec, 0x1a, 0x20, 0x28, 0xf2, 0x95,
	0xb1, 0x24, 0x30, 0x6e, 0x24, 0x51, 0xd6, 0x28, 0xbb, 0x5b, 0x79, 0xdf, 0x02, 0x1b, 0x42, 0x67,
	0x1d, 0xb8, 0xf2, 0xe4, 0x37, 0x71, 0x33, 0x89, 0xb2, 0x56, 0xf9, 0x7b, 0x4f, 0x3f, 0xe1, 0x72,
	0x62, 0x91, 0x7b, 0xfc, 0x38, 0xb4, 0x97, 0xb8, 0x0e, 0xe8, 0x3c, 0xbb, 0x81, 0x9e, 0x09, 0x56,
	0x2c, 0xb8, 0xc3, 0x8a, 0xe4, 0xae, 0xb5, 0x59, 0x42, 0x4d, 0x53, 0xc9, 0xae, 0xa0, 0x45, 0x1e,
	0x57, 0x2e, 0x6e, 0x24, 0xcd, 0xac, 0x37, 0x6a, 0xe5, 0xdb, 0x69, 0xcb, 0xbd, 0xa5, 0x63, 0xe8,
	0xff, 0x8f, 0x75, 0x46, 0x2b, 0x87, 0x2c, 0x83, 0x0b, 0x89, 0x5c, 0x2e, 0x49, 0x61, 0x45, 0xaa,
	0x92, 0x7c, 0xe3, 0x0e, 0xe1, 0xe7, 0xb5, 0x4f, 0xd5, 0x2b, 0xdf, 0xb8, 0xd1, 0x1b, 0x74, 0xea,
	0xd7, 0xec, 0x19, 0xda, 0xfb, 0x3c, 0xd6, 0xcf, 0x8f, 0xce, 0x3b, 0x1c, 0xe4, 0xc7, 0x0b, 0xd3,
	0x93, 0xf1, 0xcb, 0xd7, 0xd3, 0x9c, 0xfc, 0x22, 0xcc, 0x8a, 0x65, 0x10, 0xdc, 0x71, 0x25, 0x2d,
	0x97, 0xf8, 0x78, 0x3f, 0x2a, 0x56, 0x24, 0xac, 0x76, 0x68, 0xbf, 0x49, 0xa0, 0xbb, 0xdb, 0xfd,
	0x7b, 0x31, 0xd7, 0x4b, 0xfe, 0x67, 0x1b, 0xb3, 0xf6, 0x8e, 0x1f, 0x7e, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xaa, 0xde, 0x7d, 0x54, 0xa9, 0x01, 0x00, 0x00,
}
